
<!-- Generated by ai2html v0.100.0 - 2024-10-10 13:09 -->
<!-- ai file: crown.ai -->
<style lang="scss">
	#g-crown-box ,
	#g-crown-box .g-artboard {
		margin:0 auto;
	}
	#g-crown-box p {
		margin:0;
	}
	#g-crown-box .g-aiAbs {
		position:absolute;
	}
	#g-crown-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-crown-box .g-aiPointText p { white-space: nowrap; }
	#g-crown-Artboard_84 {
		position:relative;
		overflow:hidden;
	}
	#g-crown-Artboard_84 p {
		font-weight:700;
		line-height:10px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:8px;
		text-align:left;
		color:rgb(252,252,252);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-crown-Artboard_84 .g-pstyle0 {
		height:10px;
	}
	#g-crown-Artboard_84 .g-pstyle1 {
		font-weight:500;
		height:10px;
		text-align:center;
		color:rgb(244,240,191);
	}

	/* Custom CSS */


</style>

<div id="g-crown-box" bind:clientWidth={width}>

	<!-- Artboard: Artboard_84 -->
{#if width && (width >= 0)}	<div id="g-crown-Artboard_84" class="g-artboard" style="">
<div style="padding: 0 0 102.2114% 0;"></div>
		<div id="g-crown-Artboard_84-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/crown-Artboard_84.png);"></div>		<div id="g-ai0-1" class="g-sm g-aiAbs g-aiPointText" style="top:22.6432%;margin-top:-5.6px;left:40.1679%;width:56px;">
			<p class="g-pstyle0">Tallahasse</p>
		</div>
		<div id="g-ai0-2" class="g-sm g-aiAbs g-aiPointText" style="top:23.9263%;margin-top:-5.6px;left:58.6544%;width:63px;">
			<p class="g-pstyle0">Jacksonville</p>
		</div>
		<div id="g-ai0-3" class="g-small-labels g-aiAbs g-aiPointText" style="top:38.6819%;margin-top:-5.6px;left:65.1263%;width:49px;">
			<p class="g-pstyle0">Orlando</p>
		</div>
		<div id="g-ai0-4" class="g-small-labels g-aiAbs g-aiPointText" style="top:45.0974%;margin-top:-5.6px;left:48.6724%;width:44px;">
			<p class="g-pstyle0">Tampa</p>
		</div>
		<div id="g-ai0-5" class="g-small-labels g-aiAbs g-aiPointText" style="top:64.344%;margin-top:-5.6px;left:65.6633%;width:43px;">
			<p class="g-pstyle0">Miami</p>
		</div>
		<div id="g-ai0-6" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.9993,0.0365,-0.0365,0.9993,0,0);transform-origin: 50% 59.0812344803122%;-webkit-transform: matrix(0.9993,0.0365,-0.0365,0.9993,0,0);-webkit-transform-origin: 50% 59.0812344803122%;-ms-transform: matrix(0.9993,0.0365,-0.0365,0.9993,0,0);-ms-transform-origin: 50% 59.0812344803122%;top:78.7522%;margin-top:-5.5px;left:68.7508%;margin-left:-38.5px;width:77px;">
			<p class="g-pstyle1">Area of interest</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-10-10 13:09 -->
