
<!-- Generated by ai2html v0.100.0 - 2024-10-10 14:44 -->
<!-- ai file: housing-2010.ai -->
<style lang="scss">
	#g-housing-2010-box ,
	#g-housing-2010-box .g-artboard {
		margin:0 auto;
	}
	#g-housing-2010-box p {
		margin:0;
	}
	#g-housing-2010-box .g-aiAbs {
		position:absolute;
	}
	#g-housing-2010-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-housing-2010-box .g-aiPointText p { white-space: nowrap; }
	#g-housing-2010-sm {
		position:relative;
		overflow:hidden;
	}
	#g-housing-2010-sm p {
		font-weight:500;
		line-height:16px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-housing-2010-sm .g-pstyle0 {
		font-weight:700;
		line-height:23px;
		height:23px;
		font-size:19px;
		text-align:center;
	}
	#g-housing-2010-sm .g-pstyle1 {
		line-height:13px;
		height:13px;
		font-size:10px;
	}
	#g-housing-2010-sm .g-pstyle2 {
		line-height:13px;
		height:13px;
		font-size:10px;
		color:rgb(51,51,51);
	}
	#g-housing-2010-sm .g-pstyle3 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-housing-2010-sm .g-pstyle4 {
		height:16px;
		text-align:right;
	}
	#g-housing-2010-sm .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(153,55,121);
	}
	#g-housing-2010-sm .g-pstyle6 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-housing-2010-sm .g-pstyle7 {
		line-height:17px;
		height:17px;
		font-size:14px;
		text-align:right;
	}
	#g-housing-2010-md {
		position:relative;
		overflow:hidden;
	}
	#g-housing-2010-md p {
		font-weight:500;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-housing-2010-md .g-pstyle0 {
		font-weight:700;
		line-height:26px;
		height:26px;
		font-size:22px;
		text-align:center;
	}
	#g-housing-2010-md .g-pstyle1 {
		line-height:13px;
		height:13px;
		font-size:11px;
	}
	#g-housing-2010-md .g-pstyle2 {
		line-height:13px;
		height:13px;
		font-size:11px;
		color:rgb(51,51,51);
	}
	#g-housing-2010-md .g-pstyle3 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-housing-2010-md .g-pstyle4 {
		height:17px;
	}
	#g-housing-2010-md .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-housing-2010-md .g-pstyle6 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(153,55,121);
	}
	#g-housing-2010-md .g-pstyle7 {
		height:17px;
		text-align:right;
	}
	#g-housing-2010-Artboard_84 {
		position:relative;
		overflow:hidden;
	}
	#g-housing-2010-Artboard_84 p {
		font-weight:500;
		line-height:16px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-housing-2010-Artboard_84 .g-pstyle0 {
		font-weight:700;
		line-height:24px;
		height:24px;
		font-size:20px;
		text-align:center;
	}
	#g-housing-2010-Artboard_84 .g-pstyle1 {
		line-height:11px;
		height:11px;
		font-size:9px;
	}
	#g-housing-2010-Artboard_84 .g-pstyle2 {
		line-height:11px;
		height:11px;
		font-size:9px;
		color:rgb(51,51,51);
	}
	#g-housing-2010-Artboard_84 .g-pstyle3 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-housing-2010-Artboard_84 .g-pstyle4 {
		height:16px;
	}
	#g-housing-2010-Artboard_84 .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-housing-2010-Artboard_84 .g-pstyle6 {
		line-height:17px;
		height:17px;
		font-size:14px;
		text-align:right;
	}

	/* Custom CSS */


</style>

<div id="g-housing-2010-box" bind:clientWidth={width}>

	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <660)}	<div id="g-housing-2010-sm" class="g-artboard" style="">
<div style="padding: 0 0 203.7696% 0;"></div>
		<div id="g-housing-2010-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/housing-2010-sm.png);"></div>		<div id="g-ai0-1" class="g-legend_copy g-aiAbs g-aiPointText" style="top:3.8778%;margin-top:-24.3px;left:50.046%;margin-left:-112px;width:224px;">
			<p class="g-pstyle0">Percentage of newly-built</p>
			<p class="g-pstyle0">housing since 2010</p>
		</div>
		<div id="g-ai0-2" class="g-legend g-aiAbs g-aiPointText" style="top:8.505%;margin-top:-7.4px;left:32.8024%;width:36px;">
			<p class="g-pstyle1">5%</p>
		</div>
		<div id="g-ai0-3" class="g-legend g-aiAbs g-aiPointText" style="top:8.505%;margin-top:-7.4px;left:40.4362%;width:42px;">
			<p class="g-pstyle1">10%</p>
		</div>
		<div id="g-ai0-4" class="g-legend g-aiAbs g-aiPointText" style="top:8.505%;margin-top:-7.4px;left:49.3117%;width:42px;">
			<p class="g-pstyle1">20%</p>
		</div>
		<div id="g-ai0-5" class="g-legend g-aiAbs g-aiPointText" style="top:8.505%;margin-top:-7.4px;left:58.1938%;width:42px;">
			<p class="g-pstyle2">40%</p>
		</div>
		<div id="g-ai0-6" class="g-legend g-aiAbs g-aiPointText" style="top:8.505%;margin-top:-7.4px;left:67.2293%;width:42px;">
			<p class="g-pstyle2">80%</p>
		</div>
		<div id="g-ai0-7" class="g-towns g-aiAbs g-aiPointText" style="top:15.75%;margin-top:-10.7px;left:36.6596%;width:103px;">
			<p class="g-pstyle3">Jacksonville</p>
		</div>
		<div id="g-ai0-8" class="g-small-labels g-aiAbs g-aiPointText" style="top:18.4967%;margin-top:-32.2px;right:2.2617%;width:190px;">
			<p class="g-pstyle4">More housing has been built </p>
			<p class="g-pstyle4">along Milton's area of </p>
			<p class="g-pstyle4">influence than the entire US </p>
			<p class="g-pstyle4">West Coast in recent years </p>
		</div>
		<div id="g-ai0-9" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.8101,-0.5863,0.5863,0.8101,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.8101,-0.5863,0.5863,0.8101,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.8101,-0.5863,0.5863,0.8101,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:40.7222%;margin-top:-7.2px;left:10.2484%;margin-left:-62.5px;width:125px;">
			<p class="g-pstyle5">Tropical storm winds</p>
		</div>
		<div id="g-ai0-10" class="g-towns g-aiAbs g-aiPointText" style="top:41.5384%;margin-top:-10.7px;left:56.8911%;width:77px;">
			<p class="g-pstyle3">Orlando</p>
		</div>
		<div id="g-ai0-11" class="g-towns g-aiAbs g-aiPointText" style="top:49.8138%;margin-top:-10.7px;left:29.6376%;width:67px;">
			<p class="g-pstyle3">Tampa</p>
		</div>
		<div id="g-ai0-12" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7739,-0.6334,0.6334,0.7739,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7739,-0.6334,0.6334,0.7739,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7739,-0.6334,0.6334,0.7739,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:56.2145%;margin-top:-7.2px;left:45.0158%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle6">Hurricane path</p>
		</div>
		<div id="g-ai0-13" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.797,-0.604,0.604,0.797,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.797,-0.604,0.604,0.797,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.797,-0.604,0.604,0.797,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:74.9785%;margin-top:-7.2px;left:14.1278%;margin-left:-51px;width:102px;">
			<p class="g-pstyle6">Hurricane winds</p>
		</div>
		<div id="g-ai0-14" class="g-towns g-aiAbs g-aiPointText" style="top:80.5098%;margin-top:-10.7px;left:87.262%;width:65px;">
			<p class="g-pstyle3">Miami</p>
		</div>
		<div id="g-ai0-15" class="g-small-labels g-aiAbs g-aiPointText" style="top:88.7955%;margin-top:-17.8px;right:58.4011%;width:145px;">
			<p class="g-pstyle7">Areas with no</p>
			<p class="g-pstyle7">significant increase</p>
		</div>
	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 660)}	<div id="g-housing-2010-md" class="g-artboard" style="">
<div style="padding: 0 0 157.2206% 0;"></div>
		<div id="g-housing-2010-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/housing-2010-md.png);"></div>		<div id="g-ai1-1" class="g-legend_copy g-aiAbs g-aiPointText" style="top:4.1266%;margin-top:-27.8px;left:51.0596%;margin-left:-130px;width:260px;">
			<p class="g-pstyle0">Percentage of newly-built </p>
			<p class="g-pstyle0">housing since 2010</p>
		</div>
		<div id="g-ai1-2" class="g-legend g-aiAbs g-aiPointText" style="top:8.885%;margin-top:-7.2px;left:33.8761%;width:36px;">
			<p class="g-pstyle1">5%</p>
		</div>
		<div id="g-ai1-3" class="g-legend g-aiAbs g-aiPointText" style="top:8.885%;margin-top:-7.2px;left:41.5974%;width:43px;">
			<p class="g-pstyle1">10%</p>
		</div>
		<div id="g-ai1-4" class="g-legend g-aiAbs g-aiPointText" style="top:8.885%;margin-top:-7.2px;left:50.5744%;width:43px;">
			<p class="g-pstyle1">20%</p>
		</div>
		<div id="g-ai1-5" class="g-legend g-aiAbs g-aiPointText" style="top:8.885%;margin-top:-7.2px;left:59.5582%;width:43px;">
			<p class="g-pstyle2">40%</p>
		</div>
		<div id="g-ai1-6" class="g-legend g-aiAbs g-aiPointText" style="top:8.885%;margin-top:-7.2px;left:68.6972%;width:43px;">
			<p class="g-pstyle2">80%</p>
		</div>
		<div id="g-ai1-7" class="g-towns g-aiAbs g-aiPointText" style="top:14.2319%;margin-top:-10.7px;left:51.4799%;width:103px;">
			<p class="g-pstyle3">Jacksonville</p>
		</div>
		<div id="g-ai1-8" class="g-towns g-aiAbs g-aiPointText" style="top:14.6173%;margin-top:-10.7px;left:5.5667%;width:90px;">
			<p class="g-pstyle3">Tallahasse</p>
		</div>
		<div id="g-ai1-9" class="g-labels g-aiAbs g-aiPointText" style="top:35.1355%;margin-top:-34.6px;left:3.2363%;width:218px;">
			<p class="g-pstyle4">More housing has been built </p>
			<p class="g-pstyle4">along Milton's potential area of </p>
			<p class="g-pstyle4">influence than the entire US </p>
			<p class="g-pstyle4">West Coast in recent years </p>
		</div>
		<div id="g-ai1-10" class="g-towns g-aiAbs g-aiPointText" style="top:40.8303%;margin-top:-10.7px;left:65.311%;width:77px;">
			<p class="g-pstyle3">Orlando</p>
		</div>
		<div id="g-ai1-11" class="g-towns g-aiAbs g-aiPointText" style="top:49.0218%;margin-top:-10.7px;left:44.2515%;width:67px;">
			<p class="g-pstyle3">Tampa</p>
		</div>
		<div id="g-ai1-12" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:55.6249%;margin-top:-7.2px;left:55.7055%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle5">Hurricane path</p>
		</div>
		<div id="g-ai1-13" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7862,-0.618,0.618,0.7862,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:72.779%;margin-top:-7.2px;left:36.0896%;margin-left:-51px;width:102px;">
			<p class="g-pstyle5">Hurricane winds</p>
		</div>
		<div id="g-ai1-14" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7606,-0.6493,0.6493,0.7606,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7606,-0.6493,0.6493,0.7606,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7606,-0.6493,0.6493,0.7606,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:80.4887%;margin-top:-7.2px;left:45.0423%;margin-left:-62.5px;width:125px;">
			<p class="g-pstyle6">Tropical storm winds</p>
		</div>
		<div id="g-ai1-15" class="g-towns g-aiAbs g-aiPointText" style="top:80.246%;margin-top:-10.7px;left:89.5774%;width:65px;">
			<p class="g-pstyle3">Miami</p>
		</div>
		<div id="g-ai1-16" class="g-small-labels g-aiAbs g-aiPointText" style="top:90.5681%;margin-top:-17.8px;right:41.4278%;width:145px;">
			<p class="g-pstyle7">Areas with no</p>
			<p class="g-pstyle7">significant increase</p>
		</div>
	</div>
{/if}
	<!-- Artboard: Artboard_84 -->
{#if width && ( width >= 0 && width <510)}	<div id="g-housing-2010-Artboard_84" class="g-artboard" style="">
<div style="padding: 0 0 291.1654% 0;"></div>
		<div id="g-housing-2010-Artboard_84-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/housing-2010-Artboard_84.png);"></div>		<div id="g-ai2-1" class="g-legend_copy g-aiAbs g-aiPointText" style="top:3.6367%;margin-top:-25.5px;left:49.976%;margin-left:-117px;width:234px;">
			<p class="g-pstyle0">Percentage of newly-built</p>
			<p class="g-pstyle0">housing since 2010</p>
		</div>
		<div id="g-ai2-2" class="g-legend g-aiAbs g-aiPointText" style="top:8.5166%;margin-top:-6.1px;left:25.38%;width:34px;">
			<p class="g-pstyle1">5%</p>
		</div>
		<div id="g-ai2-3" class="g-legend g-aiAbs g-aiPointText" style="top:8.5166%;margin-top:-6.1px;left:38.1969%;width:39px;">
			<p class="g-pstyle1">10%</p>
		</div>
		<div id="g-ai2-4" class="g-legend g-aiAbs g-aiPointText" style="top:8.5166%;margin-top:-6.1px;left:74.8302%;width:39px;">
			<p class="g-pstyle2">80%</p>
		</div>
		<div id="g-ai2-5" class="g-legend g-aiAbs g-aiPointText" style="top:8.5166%;margin-top:-6.1px;left:62.4792%;width:39px;">
			<p class="g-pstyle2">40%</p>
		</div>
		<div id="g-ai2-6" class="g-legend g-aiAbs g-aiPointText" style="top:8.5166%;margin-top:-6.1px;left:50.4345%;width:39px;">
			<p class="g-pstyle1">20%</p>
		</div>
		<div id="g-ai2-7" class="g-towns g-aiAbs g-aiPointText" style="top:15.7553%;margin-top:-10.7px;left:30.7383%;width:103px;">
			<p class="g-pstyle3">Jacksonville</p>
		</div>
		<div id="g-ai2-8" class="g-small-labels g-aiAbs g-aiPointText" style="top:26.6784%;margin-top:-32.2px;left:6.2248%;width:190px;">
			<p class="g-pstyle4">More housing has been built </p>
			<p class="g-pstyle4">along Milton's area of </p>
			<p class="g-pstyle4">influence than the entire US </p>
			<p class="g-pstyle4">West Coast in recent years </p>
		</div>
		<div id="g-ai2-9" class="g-towns g-aiAbs g-aiPointText" style="top:43.2311%;margin-top:-10.7px;left:61.5385%;width:77px;">
			<p class="g-pstyle3">Orlando</p>
		</div>
		<div id="g-ai2-10" class="g-towns g-aiAbs g-aiPointText" style="top:51.9454%;margin-top:-10.7px;left:20.048%;width:67px;">
			<p class="g-pstyle3">Tampa</p>
		</div>
		<div id="g-ai2-11" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7971,-0.6039,0.6039,0.7971,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7971,-0.6039,0.6039,0.7971,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7971,-0.6039,0.6039,0.7971,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:58.6624%;margin-top:-7.2px;left:44.1845%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle5">Hurricane path</p>
		</div>
		<div id="g-ai2-12" class="g-small-labels g-aiAbs g-aiPointText" style="top:91.4272%;margin-top:-17.8px;right:49.9745%;width:145px;">
			<p class="g-pstyle6">Areas with no</p>
			<p class="g-pstyle6">significant increase</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-10-10 14:44 -->
