
<!-- Generated by ai2html v0.100.0 - 2024-10-11 09:49 -->
<!-- ai file: population-change.ai -->
<style lang="scss">
	#g-population-change-box ,
	#g-population-change-box .g-artboard {
		margin:0 auto;
	}
	#g-population-change-box p {
		margin:0;
	}
	#g-population-change-box .g-aiAbs {
		position:absolute;
	}
	#g-population-change-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-population-change-box .g-aiPointText p { white-space: nowrap; }
	#g-population-change-sm {
		position:relative;
		overflow:hidden;
	}
	#g-population-change-sm p {
		font-weight:500;
		line-height:16px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-population-change-sm .g-pstyle0 {
		font-weight:700;
		line-height:20px;
		height:20px;
		font-size:17px;
		text-align:center;
	}
	#g-population-change-sm .g-pstyle1 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
	}
	#g-population-change-sm .g-pstyle2 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
		color:rgb(51,51,51);
	}
	#g-population-change-sm .g-pstyle3 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-population-change-sm .g-pstyle4 {
		height:16px;
		text-align:right;
	}
	#g-population-change-sm .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-population-change-sm .g-pstyle6 {
		height:16px;
	}
	#g-population-change-sm .g-pstyle7 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(177,132,98);
	}
	#g-population-change-sm .g-pstyle8 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(153,55,121);
	}
	#g-population-change-md {
		position:relative;
		overflow:hidden;
	}
	#g-population-change-md p {
		font-weight:500;
		line-height:16px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-population-change-md .g-pstyle0 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-population-change-md .g-pstyle1 {
		height:16px;
	}
	#g-population-change-md .g-pstyle2 {
		font-weight:700;
		line-height:20px;
		height:20px;
		font-size:17px;
		text-align:center;
	}
	#g-population-change-md .g-pstyle3 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
	}
	#g-population-change-md .g-pstyle4 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
		color:rgb(51,51,51);
	}
	#g-population-change-md .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-population-change-md .g-pstyle6 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(177,132,98);
	}
	#g-population-change-md .g-pstyle7 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(153,55,121);
	}
	#g-population-change-Artboard_82 {
		position:relative;
		overflow:hidden;
	}
	#g-population-change-Artboard_82 p {
		font-weight:500;
		line-height:16px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-population-change-Artboard_82 .g-pstyle0 {
		font-weight:700;
		line-height:20px;
		height:20px;
		font-size:17px;
		text-align:center;
	}
	#g-population-change-Artboard_82 .g-pstyle1 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
	}
	#g-population-change-Artboard_82 .g-pstyle2 {
		line-height:12px;
		height:12px;
		font-size:10px;
		text-align:right;
		color:rgb(51,51,51);
	}
	#g-population-change-Artboard_82 .g-pstyle3 {
		font-weight:700;
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(252,252,252);
	}
	#g-population-change-Artboard_82 .g-pstyle4 {
		height:16px;
		text-align:right;
	}
	#g-population-change-Artboard_82 .g-pstyle5 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(175,133,102);
	}
	#g-population-change-Artboard_82 .g-pstyle6 {
		height:16px;
	}
	#g-population-change-Artboard_82 .g-pstyle7 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(177,132,98);
	}
	#g-population-change-Artboard_82 .g-pstyle8 {
		line-height:13px;
		height:13px;
		font-size:11px;
		text-align:center;
		color:rgb(153,55,121);
	}

	/* Custom CSS */


</style>

<div id="g-population-change-box" bind:clientWidth={width}>

	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <660)}	<div id="g-population-change-sm" class="g-artboard" style="">
<div style="padding: 0 0 196.7108% 0;"></div>
		<div id="g-population-change-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/population-change-sm.png);"></div>		<div id="g-ai0-1" class="g-legend_copy g-aiAbs g-aiPointText" style="top:3.3145%;margin-top:-11.3px;left:51.2767%;margin-left:-89.5px;width:179px;">
			<p class="g-pstyle0">Increase in population</p>
		</div>
		<div id="g-ai0-2" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.9441%;margin-top:-6.6px;right:64.7443%;width:33px;">
			<p class="g-pstyle1">2k</p>
		</div>
		<div id="g-ai0-3" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.9441%;margin-top:-6.6px;right:55.015%;width:33px;">
			<p class="g-pstyle1">9k</p>
		</div>
		<div id="g-ai0-4" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.9441%;margin-top:-6.6px;right:44.9888%;width:39px;">
			<p class="g-pstyle1">17k</p>
		</div>
		<div id="g-ai0-5" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.9441%;margin-top:-6.6px;right:35.2553%;width:39px;">
			<p class="g-pstyle2">33k</p>
		</div>
		<div id="g-ai0-6" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.9441%;margin-top:-6.6px;right:25.622%;width:39px;">
			<p class="g-pstyle2">73k</p>
		</div>
		<div id="g-ai0-7" class="g-towns g-aiAbs g-aiPointText" style="top:12.7268%;margin-top:-10.7px;left:35.4644%;width:103px;">
			<p class="g-pstyle3">Jacksonville</p>
		</div>
		<div id="g-ai0-8" class="g-labels g-aiAbs g-aiPointText" style="top:25.6395%;margin-top:-32.2px;right:49.4708%;width:225px;">
			<p class="g-pstyle4">1.5 million people </p>
			<p class="g-pstyle4">moved to the Orlando metro area </p>
			<p class="g-pstyle4">in the past decade, a 50% increase </p>
			<p class="g-pstyle4">over  it's 2010 population </p>
		</div>
		<div id="g-ai0-9" class="g-towns g-aiAbs g-aiPointText" style="top:39.4406%;margin-top:-10.7px;left:54.9302%;width:77px;">
			<p class="g-pstyle3">Orlando</p>
		</div>
		<div id="g-ai0-10" class="g-towns g-aiAbs g-aiPointText" style="top:48.0129%;margin-top:-10.7px;left:26.9006%;width:67px;">
			<p class="g-pstyle3">Tampa</p>
		</div>
		<div id="g-ai0-11" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7947,-0.607,0.607,0.7947,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7947,-0.607,0.607,0.7947,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7947,-0.607,0.607,0.7947,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:53.9456%;margin-top:-7.2px;left:43.9201%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle5">Hurricane path</p>
		</div>
		<div id="g-ai0-12" class="g-labels g-aiAbs g-aiPointText" style="top:57.9154%;margin-top:-40px;left:1.985%;width:141px;">
			<p class="g-pstyle6">Riverview, a suburb </p>
			<p class="g-pstyle6">of Tampa, almost </p>
			<p class="g-pstyle6">doubled it's housing </p>
			<p class="g-pstyle6">stock from 25k to </p>
			<p class="g-pstyle6">45k units.</p>
		</div>
		<div id="g-ai0-13" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:70.0935%;margin-top:-7.2px;left:22.6885%;margin-left:-51px;width:102px;">
			<p class="g-pstyle7">Hurricane winds</p>
		</div>
		<div id="g-ai0-14" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7777,-0.6286,0.6286,0.7777,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7777,-0.6286,0.6286,0.7777,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7777,-0.6286,0.6286,0.7777,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:77.4697%;margin-top:-7.2px;left:34.3134%;margin-left:-62.5px;width:125px;">
			<p class="g-pstyle8">Tropical storm winds</p>
		</div>
		<div id="g-ai0-15" class="g-towns g-aiAbs g-aiPointText" style="top:79.8104%;margin-top:-10.7px;left:85.3013%;width:65px;">
			<p class="g-pstyle3">Miami</p>
		</div>
	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 660)}	<div id="g-population-change-md" class="g-artboard" style="">
<div style="padding: 0 0 141.0481% 0;"></div>
		<div id="g-population-change-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/population-change-md.png);"></div>		<div id="g-ai1-1" class="g-towns g-aiAbs g-aiPointText" style="top:5.1216%;margin-top:-10.7px;left:5.5846%;width:90px;">
			<p class="g-pstyle0">Tallahasse</p>
		</div>
		<div id="g-ai1-2" class="g-towns g-aiAbs g-aiPointText" style="top:6.9478%;margin-top:-10.7px;left:57.039%;width:103px;">
			<p class="g-pstyle0">Jacksonville</p>
		</div>
		<div id="g-ai1-3" class="g-labels g-aiAbs g-aiPointText" style="top:20.9494%;margin-top:-40px;left:77.7351%;width:168px;">
			<p class="g-pstyle1">1.5 million people </p>
			<p class="g-pstyle1">moved to the Orlando</p>
			<p class="g-pstyle1">metro area in the past </p>
			<p class="g-pstyle1">decade, a 50% increase </p>
			<p class="g-pstyle1">over it's 2010 population </p>
		</div>
		<div id="g-ai1-4" class="g-legend_copy g-aiAbs g-aiPointText" style="top:23.3373%;margin-top:-11.3px;left:17.2611%;margin-left:-89.5px;width:179px;">
			<p class="g-pstyle2">Increase in population</p>
		</div>
		<div id="g-ai1-5" class="g-legend-labels g-aiAbs g-aiPointText" style="top:25.9564%;margin-top:-6.6px;right:91.8123%;width:33px;">
			<p class="g-pstyle3">2k</p>
		</div>
		<div id="g-ai1-6" class="g-legend-labels g-aiAbs g-aiPointText" style="top:25.9564%;margin-top:-6.6px;right:86.154%;width:33px;">
			<p class="g-pstyle3">9k</p>
		</div>
		<div id="g-ai1-7" class="g-legend-labels g-aiAbs g-aiPointText" style="top:25.9564%;margin-top:-6.6px;right:80.27%;width:39px;">
			<p class="g-pstyle3">17k</p>
		</div>
		<div id="g-ai1-8" class="g-sm g-aiAbs g-aiPointText" style="top:25.9564%;margin-top:-6.6px;right:74.5062%;width:39px;">
			<p class="g-pstyle4">33k</p>
		</div>
		<div id="g-ai1-9" class="g-sm g-aiAbs g-aiPointText" style="top:25.9564%;margin-top:-6.6px;right:68.8142%;width:39px;">
			<p class="g-pstyle4">73k</p>
		</div>
		<div id="g-ai1-10" class="g-towns g-aiAbs g-aiPointText" style="top:34.1253%;margin-top:-10.7px;left:65.285%;width:77px;">
			<p class="g-pstyle0">Orlando</p>
		</div>
		<div id="g-ai1-11" class="g-towns g-aiAbs g-aiPointText" style="top:43.256%;margin-top:-10.7px;left:43.6256%;width:67px;">
			<p class="g-pstyle0">Tampa</p>
		</div>
		<div id="g-ai1-12" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7734,-0.634,0.634,0.7734,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7734,-0.634,0.634,0.7734,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7734,-0.634,0.634,0.7734,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:50.5088%;margin-top:-7.2px;left:55.3236%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle5">Hurricane path</p>
		</div>
		<div id="g-ai1-13" class="g-labels g-aiAbs g-aiPointText" style="top:52.8749%;margin-top:-32.2px;left:18.1774%;width:173px;">
			<p class="g-pstyle1">Riverview, a suburb </p>
			<p class="g-pstyle1">of Tampa, almost doubled</p>
			<p class="g-pstyle1">it's housing stock from </p>
			<p class="g-pstyle1">25k to 45k units.</p>
		</div>
		<div id="g-ai1-14" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:69.5223%;margin-top:-7.2px;left:35.1677%;margin-left:-51px;width:102px;">
			<p class="g-pstyle6">Hurricane winds</p>
		</div>
		<div id="g-ai1-15" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:77.5789%;margin-top:-7.2px;left:45.3535%;margin-left:-62.5px;width:125px;">
			<p class="g-pstyle7">Tropical storm winds</p>
		</div>
		<div id="g-ai1-16" class="g-towns g-aiAbs g-aiPointText" style="top:78.0604%;margin-top:-10.7px;left:89.5937%;width:65px;">
			<p class="g-pstyle0">Miami</p>
		</div>
	</div>
{/if}
	<!-- Artboard: Artboard_82 -->
{#if width && ( width >= 0 && width <510)}	<div id="g-population-change-Artboard_82" class="g-artboard" style="">
<div style="padding: 0 0 301.5556% 0;"></div>
		<div id="g-population-change-Artboard_82-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }ai2html/population-change-Artboard_82.png);"></div>		<div id="g-ai2-1" class="g-legend_copy g-aiAbs g-aiPointText" style="top:2.4296%;margin-top:-11.3px;left:52.2573%;margin-left:-89.5px;width:179px;">
			<p class="g-pstyle0">Increase in population</p>
		</div>
		<div id="g-ai2-2" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.0726%;margin-top:-6.6px;right:73.0342%;width:33px;">
			<p class="g-pstyle1">2k</p>
		</div>
		<div id="g-ai2-3" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.0726%;margin-top:-6.6px;right:58.0435%;width:33px;">
			<p class="g-pstyle1">9k</p>
		</div>
		<div id="g-ai2-4" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.0726%;margin-top:-6.6px;right:42.8197%;width:39px;">
			<p class="g-pstyle1">17k</p>
		</div>
		<div id="g-ai2-5" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.0726%;margin-top:-6.6px;right:28.0223%;width:39px;">
			<p class="g-pstyle2">33k</p>
		</div>
		<div id="g-ai2-6" class="g-legend-labels g-aiAbs g-aiPointText" style="top:5.0726%;margin-top:-6.6px;right:12.834%;width:39px;">
			<p class="g-pstyle2">73k</p>
		</div>
		<div id="g-ai2-7" class="g-towns g-aiAbs g-aiPointText" style="top:11.4891%;margin-top:-10.7px;left:33.7197%;width:103px;">
			<p class="g-pstyle3">Jacksonville</p>
		</div>
		<div id="g-ai2-8" class="g-labels g-aiAbs g-aiPointText" style="top:25.85%;margin-top:-40px;right:41.9453%;width:174px;">
			<p class="g-pstyle4">1.5 million people moved </p>
			<p class="g-pstyle4">to the Orlando metro area </p>
			<p class="g-pstyle4">in the past decade, </p>
			<p class="g-pstyle4">a 50% increase over </p>
			<p class="g-pstyle4">it's 2010 population </p>
		</div>
		<div id="g-ai2-9" class="g-towns g-aiAbs g-aiPointText" style="top:38.3388%;margin-top:-10.7px;left:63.7123%;width:77px;">
			<p class="g-pstyle3">Orlando</p>
		</div>
		<div id="g-ai2-10" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.9191,-0.394,0.394,0.9191,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.9191,-0.394,0.394,0.9191,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.9191,-0.394,0.394,0.9191,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:43.2997%;margin-top:-7.2px;left:88.5158%;margin-left:-47.5px;width:95px;">
			<p class="g-pstyle5">Hurricane path</p>
		</div>
		<div id="g-ai2-11" class="g-towns g-aiAbs g-aiPointText" style="top:46.9547%;margin-top:-10.7px;left:21.7204%;width:67px;">
			<p class="g-pstyle3">Tampa</p>
		</div>
		<div id="g-ai2-12" class="g-labels g-aiAbs g-aiPointText" style="top:56.7072%;margin-top:-40px;left:8.8198%;width:141px;">
			<p class="g-pstyle6">Riverview, a suburb </p>
			<p class="g-pstyle6">of Tampa, almost </p>
			<p class="g-pstyle6">doubled it's housing </p>
			<p class="g-pstyle6">stock from 25k to </p>
			<p class="g-pstyle6">45k units.</p>
		</div>
		<div id="g-ai2-13" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7864,-0.6177,0.6177,0.7864,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:67.8451%;margin-top:-7.2px;left:17.9838%;margin-left:-51px;width:102px;">
			<p class="g-pstyle7">Hurricane winds</p>
		</div>
		<div id="g-ai2-14" class="g-small-labels g-aiAbs g-aiPointText" style="transform: matrix(0.7871,-0.6168,0.6168,0.7871,0,0);transform-origin: 50% 56.9489685124864%;-webkit-transform: matrix(0.7871,-0.6168,0.6168,0.7871,0,0);-webkit-transform-origin: 50% 56.9489685124864%;-ms-transform: matrix(0.7871,-0.6168,0.6168,0.7871,0,0);-ms-transform-origin: 50% 56.9489685124864%;top:75.86%;margin-top:-7.2px;left:34.6647%;margin-left:-62.5px;width:125px;">
			<p class="g-pstyle8">Tropical storm winds</p>
		</div>
		<div id="g-ai2-15" class="g-towns g-aiAbs g-aiPointText" style="top:78.9138%;margin-top:-10.7px;left:56.5126%;width:65px;">
			<p class="g-pstyle3">Miami</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-10-11 09:49 -->
